<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <base href="<?php echo $this->baseUrl(); ?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->title(); ?></title>

    <link rel="stylesheet" type="text/css" href="/libs/jquery/easyui/themes/default/easyui.css">
   	<link rel="stylesheet" type="text/css" href="/libs/jquery/easyui/themes/icon.css">
    <link rel="stylesheet" type="text/css" href="/styles/main.css">

    <script type="text/javascript" src="/js/function/scope.js"></script>
    <script type="text/javascript" src="/js/function/array.js"></script>
   	<script type="text/javascript" src="/libs/jquery/easyui/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="/libs/jquery/namespace.js"></script>
    <script type="text/javascript" src="/libs/jquery/jquery.json-2.3.min.js"></script>
   	<script type="text/javascript" src="/libs/jquery/easyui/jquery.easyui.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="/libs/jquery/moo4q/mootools-1.2.4-base.js"></script>
   	<script type="text/javascript" charset="utf-8" src="/libs/jquery/moo4q/Class.Mutators.jQuery.js"></script>

    <script type="text/javascript" src="/js/mongo-editor/menu/abstract.js"></script>

    <script type="text/javascript" src="/js/mongo-editor/data/tree.js"></script>

    <script type="text/javascript" src="/js/mongo-editor/collection/property.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/collection/property/menu.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/collection/property/edit/dialog.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/collection/property/edit/simple-form.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/collection/tree-grid.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/collection/tree-grid/menu.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/layout.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/app.js"></script>
</head>
<body class="easyui-layout mongo-editor" fit="true">
    <div id="data-region" region="center" title="DB">
        <table id="data-region-tree-grid"
               class="easyui-treegrid"
               border="false"
               idField="id"
               treeField="key"
               fit="true">
        </table>
    </div>
    <div region="north" split="true" title="Search" style="height:100px;">
    </div>
    <div region="east" split="true" title="Properties" style="width: 400px;">
        <table id="array-property-grid" class="easyui-propertygrid" scrollbarSize="0" fitColumns="true" toolbar="#toolbar" border="0">
            <div class="toolbar">
                <a href="#" class="easyui-linkbutton button save" iconCls="icon-save" plain="true">Save</a>
                <a href="#" class="easyui-linkbutton button new" iconCls="icon-add" plain="true">New</a>
                <a href="#" class="easyui-linkbutton button new-array" iconCls="icon-add" plain="true">New Array</a>
            </div>
        </table>
    </div>
    <div id="property-edit-menu" class="easyui-menu" style="width:120px;">
        <div iconCls="icon-edit" rel="edit">Edit</div>
        <div iconCls="icon-remove" rel="delete">Delete</div>

    </div>
    <div id="collection-edit-menu" class="easyui-menu" style="width:120px;">
        <div iconCls="icon-remove" rel="delete">Delete</div>
        <div iconCls="icon-add" rel="new">New</div>
        <div iconCls="icon-add" rel="newArray">New Array</div>
    </div>

    <div id="edit-property-dialog" class="easyui-dialog"
         style="width:400px; height:280px;"  title="Edit Property"
         closed="true" buttons="#edit-property-dialog-buttons">
        <div class="ftitle">Property:</div>
        <form class="simple-form" method="post">
            <div class="fitem">
                <label>Name:</label>
                <input name="name" class="easyui-validatebox" required="true">
            </div>
            <div class="fitem">
                <label>Value:</label>
                <input name="value" class="easyui-validatebox" required="true">
            </div>
        </form>
        <form class="key-form" method="post">
            <div class="fitem">
                <label>Key:</label>
                <input name="name" class="easyui-validatebox" required="true">
            </div>
        </form>
    </div>
    <div id="edit-property-dialog-buttons">
        <a href="#" class="easyui-linkbutton set" iconCls="icon-ok">Set</a>
        <a href="#" class="easyui-linkbutton cancel" iconCls="icon-cancel" onclick="javascript:$('#edit-property-dialog').dialog('close')">Cancel</a>
    </div>
</body>
</html>