<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <base href="<?php echo $this->baseUrl(); ?>" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->title(); ?></title>

    <link rel="stylesheet" type="text/css" href="/libs/jquery/easyui/themes/default/easyui.css">
   	<link rel="stylesheet" type="text/css" href="/libs/jquery/easyui/themes/icon.css">
    <link rel="stylesheet" type="text/css" href="/styles/main.css">

    <script type="text/javascript" src="/js/function/scope.js"></script>
   	<script type="text/javascript" src="/libs/jquery/easyui/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="/libs/jquery/namespace.js"></script>
   	<script type="text/javascript" src="/libs/jquery/easyui/jquery.easyui.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="/libs/jquery/moo4q/mootools-1.2.4-base.js"></script>
   	<script type="text/javascript" charset="utf-8" src="/libs/jquery/moo4q/Class.Mutators.jQuery.js"></script>

    <script type="text/javascript" src="/js/mongo-editor/collection/property.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/collection/tree-grid.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/layout.js"></script>
    <script type="text/javascript" src="/js/mongo-editor/app.js"></script>
</head>
<body class="easyui-layout mongo-editor" fit="true">
    <div id="data-region" region="center" title="DB">
        <table id="data-region-tree-grid"
               class="easyui-treegrid"
               border="false"
               idField="id"
               treeField="key"
               fit="true">
        </table>
    </div>
    <div region="north" split="true" title="Search" style="height:100px;">
    </div>
    <div region="east" split="true" title="Properties" style="width: 400px;">
        <table id="array-property-grid" class="easyui-propertygrid" scrollbarSize="0" fitColumns="true" toolbar="#toolbar" border="0">
            <div id="array-property-toolbar">
                <a href="#" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="save()">Save</a>
                <a href="#" class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="delete()">Delete</a>
            </div>
        </table>
    </div>

</body>
</html>